### PR TITLE
Fixed the API call for Up/Down-ing a habit

### PR DESCRIPTION
**Pull request by larssorenson**

### CODE REVIEW

**Comment by elssar** [comment]
I'll merge this pull request and close the others, as this seems to have all the changes made in the other two.

Thanks for the fixes, this repository has been neglected for a very long time.

**Comment by larssorenson** [comment]
Hey!
Thanks, yeah I was kind of just opening the requests as I made changes. Also, I see you added me to the repository. Do you want me to just push my changes directly (albeit to a branch in your repo) or still do the pull requests from my own fork?

**Comment by elssar** [comment]
I think it would be more convenient if you pushed your code to a feature branch on this repo. I was planning on using git-flow here. Basically, we don't touch master. There will be a develop branch from which all feature branches will be created. When a version is ready, develop will be merged to master.

Overkill, I know, but it's a process I've come to like at work and would like to use it in all my personal projects.

And since I've been using habitrpg regularly now, I think I should start working on pyhabit again. Would be nice to have someone to review my code :smile: 

PS - I'll set up the different branches in a few hours.

**Comment by larssorenson** [comment]
Perfect! I was planning on re-writing the API to reflect how [pytrello](https://github.com/sarumont/py-trello) does it. They have a more class based approach, which I think would make things more convenient for the API.
I happen to be using pytrello and pyhabit for [HabiTrello](https://github.com/larssorenson/habitrello), hence my interest in both of them simultaneously. Having them both be structured similarly will make my life easier.
What do you think?

**Comment by elssar** [comment]
You mean a base api client class, and classes for other features that use the client? Yep, sounds good.

**Comment by larssorenson** [comment]
I'll probably tackle that in the next week or so, unless you want to get at it first.

**Comment by elssar** [comment]
If I get time during the weekend, I'll give it a go. Haven't written any python code for a few months, so would love to write some

**Pull request merged**
